### ISSUE TITLE
Clicking on clear inventory spaces

### ISSUE THREAD

**Issue by MXR156** [Nowaha/Shop-by-Conjurate#5]
I'm having a few issues, Nothing that is stopping the plugin from working properly, however might be worth noteing.

Server: Paper version git-Paper-167 (MC: 1.14.4)
Plugin: Shop v2.1.1

When I click on an inventory slot that has nothing in it within a shop page, It shows the below

`[21:25:45 ERROR]: Could not pass event PageClickEvent to Shop v2.1.1
java.lang.NullPointerException: null
        at conj.Shop.interaction.Shop.ItemviewClick(Shop.java:170) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4762.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
        at conj.Shop.tools.GUI.InteractEditor(GUI.java:130) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4813.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

Also, when buying an item from a shop, if it is set to close on complete, It doesn't appear to close the page or refresh the page so if you have something that is permission based, it still shows the item until you manually close and re-open the shop page.

**Comment by MXR156** [comment]
Paper version git-Paper-167 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Shop v2.1.1

**Comment by Huskehhh** [comment]
Hey mate. Can you try this build out?
https://ci.husk.pro/job/Shop-By-Conjurate/20/artifact/target/Shop-by-Conjurate-2.1.3-SNAPSHOT.jar
Let me know how you go

**Comment by MXR156** [comment]
Thanks for that. Getting this on enable now. I had that with a plugin of mine, I just needed to add the API Version in plugin.yml

api-version: 1.13

Did you manage to look into the close on complete as well? I looked at the commit changes and I didnt spot that, but may have missed it.

`[10:50:41 ERROR]: Fatal error trying to convert Shop v2.1.3-SNAPSHOT:conj/Shop/interaction/Editor.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for CLOCK. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:294) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore.convert(Commodore.java:173) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:283) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:112) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:201) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at conj.Shop.base.Initiate.onEnable(Initiate.java:76) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-167]        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[10:50:41 ERROR]: Fatal error trying to convert Shop v2.1.3-SNAPSHOT:conj/Shop/interaction/TradeEditor.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for BLACK_STAINED_GLASS_PANE. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:294) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore.convert(Commodore.java:173) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:283) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:112) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:201) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at conj.Shop.base.Initiate.onEnable(Initiate.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-167]        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[10:50:41 ERROR]: Fatal error trying to convert Shop v2.1.3-SNAPSHOT:conj/Shop/interaction/Shop.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for BLACK_STAINED_GLASS_PANE. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:294) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore.convert(Commodore.java:173) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:283) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:112) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:201) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at conj.Shop.base.Initiate.onEnable(Initiate.java:78) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-167]        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[10:50:41 ERROR]: Fatal error trying to convert Shop v2.1.3-SNAPSHOT:conj/Shop/interaction/PageProperties.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for CLOCK. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:294) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2210) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:688) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore.convert(Commodore.java:173) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:283) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:112) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:201) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at conj.Shop.base.Initiate.onEnable(Initiate.java:79) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-167]        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**Comment by MXR156** [comment]
Also, When clicking a blank inventory slot I now receive

`[10:59:18 ERROR]: Could not pass event PageClickEvent to Shop v2.1.3-SNAPSHOT
java.lang.NullPointerException: null
        at conj.Shop.interaction.Shop.ItemviewClick(Shop.java:170) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor439.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
        at conj.Shop.tools.GUI.InteractEditor(GUI.java:130) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor523.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**Comment by Huskehhh** [comment]
Awesome. Did some testing, think this is now resolved!
https://ci.husk.pro/job/Shop-By-Conjurate/lastSuccessfulBuild/artifact/target/Shop-by-Conjurate-2.1.3-SNAPSHOT.jar

**Comment by MXR156** [comment]
That has fixed the issues I was seeing, However brought on another.

Now when you try to move an item into a blank space (Right click then select a slot) it doesn't move it there.

Apologies, I appear to be breaking more bits.

Made a recording of the issue here if this helps - https://www.youtube.com/watch?v=lriWqeSNDjM

**Comment by Huskehhh** [comment]
Sweet man, thanks for that!
I did some more testing and fiddling and I think I've hit the nail on the head!
https://ci.husk.pro/job/Shop-By-Conjurate/lastSuccessfulBuild/artifact/target/Shop-by-Conjurate-2.1.3-SNAPSHOT.jar

Give it a go when you get a chance! :)

Thanks heaps for the issue report 👍

**Comment by MXR156** [comment]
No more errors, and it's moving the items as it used to so that's all great! Thank you!

That being said, It still doesn't seem to close the page once a purchase is complete. It leaves it open. I am sure I can put a command in to get it to do this, but thought I would let you know.

**Comment by Huskehhh** [comment]
I'll look into fixing that for you! There seems to be an option for it in the code but I'll have to find where about it is adjusted. :)

**Comment by Huskehhh** [comment]
> 
> 
> No more errors, and it's moving the items as it used to so that's all great! Thank you!
> 
> That being said, It still doesn't seem to close the page once a purchase is complete. It leaves it open. I am sure I can put a command in to get it to do this, but thought I would let you know.

I just tested the shop with close on transaction true/false and both worked. Are you using /shop page properties to edit it?

**Comment by MXR156** [comment]
Yeah I tried that. Although, it could be that it's a permission purchase that might be the one that doesn't close. If there is a command to close it then I can just use that.

**Comment by Huskehhh** [comment]
Hey mate. Just had a look again into it, I now see what the issue was. It did only pertain to command based purchases. Download new build and try again now! Thanks

**Comment by MXR156** [comment]
All looks perfect now. Thank you for the assistance, Much appreciated :D
